### ISSUE TITLE
Create library module that implements the Absinthe.Subscription.PubSub behaviour

### ISSUE THREAD

**Issue by pzingg** [easco/absinthe_apollo_sockets#11]
The two current examples both implement the same Absinthe.Subscription.PubSub behavior, except for their names, and node names, in ApolloCowboyExample.Absinthe.PubSub and PhoenixSample.Absinthe.PubSub.

This code could be moved inside the library as a macro, to eliminate redundancy. Then applications would just specify the new module (I suggest "ApolloSocket.Absinthe.PubSub") as a parameter to Absinthe.Subscription in their start up.

The `Absinthe.Phoenix.Endpoint` module in the Absinthe GitHub repository can be used as a guide on how this can be set up.

**Comment by easco** [comment]
Thank you for the suggestion, but the PubSub in the example code is just that, an example implementation - not a recommendation on the correct way to implement Absinthe's pub sub system.
